name: WolGate
version: "1.0.7"
slug: wolgate
startup: application
stage: stable
host_network: true
description: The Home Assistant Add-on for a Connected and Eco-responsible Home
url: https://github.com/StephanGR/ha-addons/tree/main/wolgate
arch:
  - armv7
  - armhf
  - aarch64
  - amd64
  - i386
options:
  domains:
    - url: https://sub1.domain.com
      macAddress: 11:22:33:44:55:66
      broadcastAddress: 255.255.255.255:9
      wakeUpIp: 192.168.1.10
      wakeUpPort: 81
      forwardIp: 192.168.1.5
      forwardPort: 1234
      wakeUpEndpoints:
        - /Users/Me
        - /Branding/Configuration
    - url: https://sub2.domain.com
      macAddress: 11:22:33:44:55:66
      broadcastAddress: 255.255.255.255:9
      wakeUpIp: 192.168.1.10
      wakeUpPort: 1234
      forwardIp: 192.168.1.6
      forwardPort: 1234
      wakeUpEndpoints: []
schema:
  domains:
    - url: str
      macAddress: str
      broadcastAddress: str
      wakeUpIp: str
      wakeUpPort: int
      forwardIp: str
      forwardPort: int
      wakeUpEndpoints:
        - str?