name: WolGate
version: "1.0.1"
slug: wolgate
startup: application
stage: stable
host_network: true
description: Description of wolgate
url: https://github.com/StephanGR/ha-addons/tree/main/wolgate
arch:
  - armv7
  - armhf
  - aarch64
  - amd64
  - i386
options:
  domains:
    - url: https://sub1.domain.com
      macAddress: 11:22:33:44:55:66
      broadcastAddress: 255.255.255.255:9
      ipAddress: 192.168.1.5
      port: 1234
schema:
  domains:
    - url: str
      macAddress: str
      broadcastAddress: str
      address: str
      port: int