name: WolGate
version: 1.0.0
slug: wol-gate
description: WolGate description
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: system
stage: stable
options:
  option1: ""
  option2: true
schema:
  option1: "str"
  option2: "bool"