name: WolGate
version: 1.0.0
slug: wol-gate
description: WolGate description
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: system
stage: stable
Wake On Lan:
  macAddress: ""
  broadcastAddress: "255.255.255.255:9"
Proxy Server:
  host: "localhost"
  port: 25565
schema:
  option1: "str"
  option2: "bool"