name: "WolGate"
version: "1.0.0"
slug: "wol-gate"
description: "WolGate description"
arch:
  - amd64
  - armhf
  - armv7
  - aarch64
  - i386
options:
  wol_macAddress:
    description: "Adresse MAC pour le Wake On Lan"
    required: true
    type: string
  wol_broadcastAddress:
    description: "Adresse de broadcast pour le Wake On Lan"
    required: true
    type: string
  proxyServer_host:
    description: "Hôte pour le serveur proxy"
    required: true
    type: string
  proxyServer_port:
    description: "Port pour le serveur proxy"
    required: true
    type: int
  domains:
    description: "Configuration des domaines en format JSON"
    required: true
    type: json
