{
  "name": "WolGate",
  "version": "1.0",
  "slug": "wolgate",
  "description": "Description of wolgate",
  "url": "https://github.com/StephanGR/ha-addons/tree/main/wolgate",
  "arch": [
    "armv7",
    "armhf",
    "aarch64",
    "amd64",
    "i386"
  ],
  "ports": {
    "25565/tcp": 25565
  },
  "ports_description": {
    "25565/tcp": "Port on which application is running"
  },
  "options": {
    "config_files": []
  },
  "schema": {
    "config_files": ["match(/(share|config)/.+)"]
  }
}